#  03_Overlap.R
# Candidate miRNA Overlap Analysis

# Description:
# This script identifies candidate miRNAs shared between
# three monocyte subsets:
#
#   1. Classical monocytes (CLAS)
#   2. Intermediate monocytes (INT)
#   3. Non-classical monocytes (NONCLAS)
#
# Candidate miRNAs are obtained from the differential
# expression results generated by:
#
#   scripts/02_DE_Volcano.R
#
# Only miRNAs classified as differential expression
# candidates (status != "NotSig") are included.
#
# The script:
#   - Calculates overlap between the three cell types
#   - Generates a three-set Venn diagram
#   - Identifies miRNAs shared by >= 2 cell types
#   - Compares the direction of logFC across cell types
#   - Generates a compact shared-miRNA table
#
# Direction interpretation:
#   Positive logFC = higher expression in High Pain
#   Negative logFC = higher expression in Low Pain
#
# Outputs:
#   results/Overlap/
#       Shared_candidate_miRNAs.csv
#       Venn_with_shared_table.pdf
#       Venn_with_shared_table.tiff
#
# Required R packages:
#   ggplot2
#   dplyr
#   tidyr
#   ggforce
#   patchwork
#   ragg

# 1. Clear R environment


rm(list = ls())


# 2. Load required packages


required_packages <-
  c(
    "ggplot2",
    "dplyr",
    "tidyr",
    "ggforce",
    "patchwork",
    "ragg"
  )


# Check whether all required packages are installed

missing_packages <-
  required_packages[
    !sapply(
      required_packages,
      requireNamespace,
      quietly = TRUE
    )
  ]


if (length(missing_packages) > 0) {
  
  stop(
    paste0(
      "Missing R package(s): ",
      paste(
        missing_packages,
        collapse = ", "
      ),
      "\nPlease install them before running this script."
    )
  )
  
}


# Load packages

library(ggplot2)
library(dplyr)
library(tidyr)
library(ggforce)
library(patchwork)
library(ragg)


# 3. Define input and output paths

# All paths are relative to the OA-Pain project root.
#

de_dir <-
  "results/DE"

overlap_dir <-
  "results/Overlap"


# Create output directory

dir.create(
  overlap_dir,
  recursive = TRUE,
  showWarnings = FALSE
)


# 4. Read DE results

# DE results are generated by scripts/02_DE_Volcano.R.
#

CLAS <-
  read.csv(
    file.path(
      de_dir,
      "CLAS_DE_all.csv"
    )
  ) |>
  filter(
    status != "NotSig"
  )


INT <-
  read.csv(
    file.path(
      de_dir,
      "INT_DE_all.csv"
    )
  ) |>
  filter(
    status != "NotSig"
  )


NONCLAS <-
  read.csv(
    file.path(
      de_dir,
      "NONCLAS_DE_all.csv"
    )
  ) |>
  filter(
    status != "NotSig"
  )


# 5. Create candidate miRNA sets


A <-
  unique(
    CLAS$miRNA
  )

B <-
  unique(
    INT$miRNA
  )

C <-
  unique(
    NONCLAS$miRNA
  )


cat(
  "\nCandidate miRNAs:\n"
)

cat(
  "CLAS:",
  length(A),
  "\n"
)

cat(
  "INT:",
  length(B),
  "\n"
)

cat(
  "NONCLAS:",
  length(C),
  "\n"
)


# 6. Calculate Venn diagram counts

venn_counts <-
  data.frame(
    
    label =
      c(
        # CLAS only
        length(
          setdiff(
            A,
            union(B, C)
          )
        ),
        
        # INT only
        length(
          setdiff(
            B,
            union(A, C)
          )
        ),
        
        # NONCLAS only
        length(
          setdiff(
            C,
            union(A, B)
          )
        ),
        
        # CLAS + INT only
        length(
          setdiff(
            intersect(A, B),
            C
          )
        ),
        
        # CLAS + NONCLAS only
        length(
          setdiff(
            intersect(A, C),
            B
          )
        ),
        
        # INT + NONCLAS only
        length(
          setdiff(
            intersect(B, C),
            A
          )
        ),
        
        # Shared by all three
        length(
          Reduce(
            intersect,
            list(A, B, C)
          )
        )
      ),
    
    x =
      c(
        -0.91,
        0.91,
        0,
        0,
        -0.48,
        0.48,
        0
      ),
    
    y =
      c(
        0.32,
        0.32,
        -0.72,
        0.54,
        -0.30,
        -0.30,
        -0.03
      )
  )


# 7. Define Venn diagram circles

circle_data <-
  data.frame(
    
    group =
      c(
        "CLAS",
        "INT",
        "NONCLAS"
      ),
    
    x0 =
      c(
        -0.58,
        0.58,
        0
      ),
    
    y0 =
      c(
        0.28,
        0.28,
        -0.50
      ),
    
    r =
      c(
        1.00,
        1.00,
        1.00
      ),
    
    fill =
      c(
        "#0072B2",
        "#D55E00",
        "#009E73"
      )
  )


# 8. Generate Venn diagram

p_venn <-
  ggplot() +
  
  ggforce::geom_circle(
    data = circle_data,
    
    aes(
      x0 = x0,
      y0 = y0,
      r = r,
      fill = group
    ),
    
    alpha = 0.16,
    color = "#202020",
    linewidth = 0.38
  ) +
  
  geom_text(
    data = venn_counts,
    
    aes(
      x = x,
      y = y,
      label = label
    ),
    
    size = 3.25,
    color = "#111111"
  ) +
  
  annotate(
    "text",
    x = -1.26,
    y = 1.34,
    label = "CLAS",
    size = 3.25,
    hjust = 0.5,
    color = "#111111"
  ) +
  
  annotate(
    "text",
    x = 1.26,
    y = 1.34,
    label = "INT",
    size = 3.25,
    hjust = 0.5,
    color = "#111111"
  ) +
  
  annotate(
    "text",
    x = 0,
    y = -1.68,
    label = "NONCLAS",
    size = 3.25,
    hjust = 0.5,
    color = "#111111"
  ) +
  
  scale_fill_manual(
    values =
      setNames(
        circle_data$fill,
        circle_data$group
      )
  ) +
  
  coord_fixed(
    xlim = c(-1.75, 1.75),
    ylim = c(-1.78, 1.50),
    clip = "off"
  ) +
  
  labs(
    title = "Overlap of candidate miRNAs"
  ) +
  
  theme_void(
    base_size = 8
  ) +
  
  theme(
    legend.position = "none",
    
    plot.title =
      element_text(
        size = 8.8,
        face = "plain",
        hjust = 0,
        margin = margin(b = 3)
      ),
    
    plot.margin =
      margin(
        2,
        4,
        2,
        2
      )
  )


# 9. Identify shared candidate miRNAs
#
# miRNAs present in at least two cell types are retained.
#

shared_table <-
  full_join(
    
    CLAS |>
      select(
        miRNA,
        CLAS = logFC
      ),
    
    INT |>
      select(
        miRNA,
        INT = logFC
      ),
    
    by = "miRNA"
    
  ) |>
  
  full_join(
    
    NONCLAS |>
      select(
        miRNA,
        NONCLAS = logFC
      ),
    
    by = "miRNA"
    
  ) |>
  
  mutate(
    
    n_group =
      (!is.na(CLAS)) +
      (!is.na(INT)) +
      (!is.na(NONCLAS))
    
  ) |>
  
  filter(
    n_group >= 2
  ) |>
  
  mutate(
    
    Shared =
      case_when(
        
        !is.na(CLAS) &
          !is.na(INT) &
          !is.na(NONCLAS) ~
          "CLAS-INT-NONCLAS",
        
        !is.na(CLAS) &
          !is.na(INT) ~
          "CLAS-INT",
        
        !is.na(CLAS) &
          !is.na(NONCLAS) ~
          "CLAS-NONCLAS",
        
        !is.na(INT) &
          !is.na(NONCLAS) ~
          "INT-NONCLAS"
        
      ),
    
    Direction =
      case_when(
        
        rowSums(
          cbind(
            CLAS,
            INT,
            NONCLAS
          ) > 0,
          na.rm = TRUE
        ) == n_group ~
          "High pain",
        
        rowSums(
          cbind(
            CLAS,
            INT,
            NONCLAS
          ) < 0,
          na.rm = TRUE
        ) == n_group ~
          "Low pain",
        
        TRUE ~
          "Opposite"
      )
  ) |>
  
  select(
    miRNA,
    CLAS,
    INT,
    NONCLAS,
    Shared,
    Direction
  ) |>
  
  arrange(
    Shared,
    miRNA
  )


# 10. Save complete shared-miRNA table

write.csv(
  
  shared_table,
  
  file.path(
    overlap_dir,
    "Shared_candidate_miRNAs.csv"
  ),
  
  row.names = FALSE
)


# 11. Prepare compact table for figure

table_plot <-
  shared_table |>
  
  mutate(
    
    CLAS =
      ifelse(
        is.na(CLAS),
        "--",
        sprintf(
          "%.2f",
          CLAS
        )
      ),
    
    INT =
      ifelse(
        is.na(INT),
        "--",
        sprintf(
          "%.2f",
          INT
        )
      ),
    
    NONCLAS =
      ifelse(
        is.na(NONCLAS),
        "--",
        sprintf(
          "%.2f",
          NONCLAS
        )
      )
  )


# Display a maximum of 10 shared miRNAs in the figure.
# The complete table is retained in the CSV output.

if (nrow(table_plot) > 10) {
  
  table_plot <-
    table_plot[
      1:10,
      ,
      drop = FALSE
    ]
  
}


# Stop if no shared candidate miRNAs are identified

if (nrow(table_plot) == 0) {
  
  stop(
    "No candidate miRNAs are shared by two or more cell types."
  )
  
}



table_long <-
  table_plot |>
  
  mutate(
    row = row_number()
  ) |>
  
  pivot_longer(
    
    cols =
      c(
        miRNA,
        CLAS,
        INT,
        NONCLAS,
        Shared,
        Direction
      ),
    
    names_to =
      "column",
    
    values_to =
      "value"
  )


# 13. Define table layout

column_levels <-
  c(
    "miRNA",
    "CLAS",
    "INT",
    "NONCLAS",
    "Shared",
    "Direction"
  )


column_labels <-
  c(
    "miRNA",
    "CLAS",
    "INT",
    "NONCLAS",
    "Shared",
    "Direction"
  )


column_x <-
  c(
    0.75,
    2.08,
    2.70,
    3.48,
    4.55,
    5.72
  )


names(column_x) <-
  column_levels


table_long$column <-
  factor(
    table_long$column,
    levels = column_levels
  )


table_long$x <-
  column_x[
    as.character(
      table_long$column
    )
  ]


table_long$y <-
  max(
    table_long$row
  ) -
  table_long$row +
  1


# 14. Create table header

header <-
  data.frame(
    
    column =
      factor(
        column_levels,
        levels = column_levels
      ),
    
    label =
      column_labels,
    
    x =
      column_x,
    
    y =
      max(
        table_long$y
      ) +
      1
  )


# Horizontal rules

rules <-
  data.frame(
    
    y =
      c(
        max(table_long$y) + 1.42,
        max(table_long$y) + 0.60,
        0.48
      ),
    
    linewidth =
      c(
        0.35,
        0.25,
        0.35
      )
  )


# 15. Generate shared-miRNA table

p_table <-
  ggplot() +
  
  geom_segment(
    data = rules,
    
    aes(
      x = 0.15,
      xend = 6.28,
      y = y,
      yend = y,
      linewidth = linewidth
    ),
    
    color = "#111111"
  ) +
  
  geom_text(
    data = header,
    
    aes(
      x = x,
      y = y,
      label = label
    ),
    
    size = 2.55,
    fontface = "bold",
    color = "#111111"
  ) +
  
  geom_text(
    data = table_long,
    
    aes(
      x = x,
      y = y,
      label = value
    ),
    
    size = 2.45,
    color = "#111111"
  ) +
  
  scale_linewidth_identity() +
  
  coord_cartesian(
    
    xlim =
      c(
        0.10,
        6.33
      ),
    
    ylim =
      c(
        0.34,
        max(table_long$y) + 1.58
      ),
    
    clip = "off"
  ) +
  
  labs(
    title =
      "Shared candidate miRNAs"
  ) +
  
  theme_void(
    base_size = 8
  ) +
  
  theme(
    
    plot.title =
      element_text(
        size = 8.8,
        face = "plain",
        hjust = 0,
        margin = margin(b = 3)
      ),
    
    plot.margin =
      margin(
        2,
        2,
        2,
        4
      )
  )


# 16. Combine Venn diagram and table

final_plot <-
  (
    p_venn +
      p_table +
      
      plot_layout(
        widths =
          c(
            0.88,
            1.62
          )
      )
  ) +
  
  plot_annotation(
    
    tag_levels = "a",
    tag_prefix = "",
    tag_suffix = "",
    
    theme =
      theme(
        
        plot.tag =
          element_text(
            size = 10,
            face = "bold"
          ),
        
        plot.tag.position =
          c(
            0,
            1
          ),
        
        plot.background =
          element_rect(
            fill = "white",
            color = NA
          )
      )
  )


# 17. Save figure as PDF

ggsave(
  
  filename =
    file.path(
      overlap_dir,
      "Venn_with_shared_table.pdf"
    ),
  
  plot =
    final_plot,
  
  width =
    7.2,
  
  height =
    3.45,
  
  units =
    "in",
  
  bg =
    "white",
  
  device =
    grDevices::pdf
)



# 18. Save figure as high-resolution TIFF

ggsave(
  
  filename =
    file.path(
      overlap_dir,
      "Venn_with_shared_table.tiff"
    ),
  
  plot =
    final_plot,
  
  width =
    7.2,
  
  height =
    3.45,
  
  units =
    "in",
  
  dpi =
    600,
  
  compression =
    "lzw",
  
  bg =
    "white",
  
  device =
    ragg::agg_tiff
)


# ============================================================
# 19. Finish
# ============================================================

cat(
  "\nOverlap analysis completed successfully.\n"
)

cat(
  "\nResults saved to:",
  overlap_dir,
  "\n"
)

cat(
  "\nGenerated files:\n"
)

cat(
  "- Shared_candidate_miRNAs.csv\n"
)

cat(
  "- Venn_with_shared_table.pdf\n"
)

cat(
  "- Venn_with_shared_table.tiff\n"
)